IMPORT LIBRARIES

In [1]:
import pandas as pd
import numpy as np

LOAD DATASETS

In [2]:
users = pd.read_csv(r"C:\Users\ASUS\Downloads\Users.csv")
orders = pd.read_csv(r"C:\Users\ASUS\Downloads\Orders.csv")
restaurants = pd.read_csv(r"C:\Users\ASUS\Downloads\Restaurant.csv")

CHECK SHAPE

In [3]:
print("Users:", users.shape)
print("Orders:", orders.shape)
print("Restaurants:", restaurants.shape)

Users: (100000, 6)
Orders: (150281, 6)
Restaurants: (148454, 7)

CHECK COLUMNS

In [10]:
print("Users:",users.columns)
print("Orders:",orders.columns)
print("Restaurants:",restaurants.columns)

Users: Index(['User_id', 'Name', 'Age', 'Gender', 'Marital Status', 'Occupation'], dtype='object')
Orders: Index(['order_date', 'Sales_QTY', 'Sales_amount', 'currency', 'User_id',
       'Restaurant_id'],
      dtype='object')
Restaurants: Index(['Restaurant_id', 'Name', 'Country', 'City', 'Rating', 'Rating_count',
       'Cuisine'],
      dtype='object')

CHECK DATA TYPES

In [12]:
print("Users:",users.info())
print("orders:",orders.info())
print("Restaurants:",restaurants.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   User_id         100000 non-null  int64
 1   Name            100000 non-null  object
 2   Age             100000 non-null  int64
 3   Gender          100000 non-null  object
 4   Marital Status  100000 non-null  object
 5   Occupation      100000 non-null  object
dtypes: int64(2), object(4)
memory usage: 4.6+ MB
Users: None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150281 entries, 0 to 150280
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_date     150281 non-null  object
 1   Sales_QTY      150281 non-null  int64
 2   Sales_amount   150281 non-null  int64
 3   currency       150281 non-null  object
 4   User_id        150281 non-null  int64
 5   Restaurant_id  148664 non-null  float64
dtypes: float64(1), int64(3), object(2)
memory usage: 6.9+ MB
orders: None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148454 entries, 0 to 148453
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Restaurant_id  148454 non-null  int64
 1   Name           148454 non-null  object
 2   Country        148454 non-null  object
 3   City           148454 non-null  object
 4   Rating         148454 non-null  object
 5   Rating_count   148454 non-null  object
 6   Cuisine        148454 non-null  object
dtypes: int64(1), object(6)
memory usage: 7.9+ MB
Restaurants: None

CHECKING MISSING VALUES

In [15]:
users.isnull().sum()

User_id           0
Name              0
Age               0
Gender            0
Marital Status    0
Occupation        0
dtype: int64

In [16]:
orders.isnull().sum()

order_date          0
Sales_QTY           0
Sales_amount        0
currency            0
User_id             0
Restaurant_id    1617
dtype: int64

In [17]:
restaurants.isnull().sum()

Restaurant_id    0
Name             0
Country          0
City             0
Rating           0
Rating_count     0
Cuisine          0
dtype: int64

CHECKING DUPLICATES

In [19]:
users.duplicated().sum()

np.int64(0)

In [20]:
orders.duplicated().sum()

np.int64(0)

In [21]:
restaurants.duplicated().sum()

np.int64(0)

CHECKING UNIQUE ID's

In [23]:
users["User_id"].nunique()

100000

In [24]:
orders["User_id"].nunique()

77929

In [25]:
restaurants["Restaurant_id"].nunique()

148454

CHECKING DATE RANGE

In [26]:
orders["order_date"] = pd.to_datetime(orders["order_date"])

print(orders["order_date"].min())
print(orders["order_date"].max())

2017-10-04 00:00:00
2020-06-26 00:00:00

CHECKING NUMERICAL COLUMNS

In [27]:
orders.describe()

,order_date,Sales_QTY,Sales_amount,User_id,Restaurant_id
count,150281,150281.000000,1.502810e+05,150281.000000,148664.000000
mean,2019-01-09 06:48:39.890072320,16.264997,6.564802e+03,49969.366553,363433.090513
min,2017-10-04 00:00:00,1.000000,-1.000000e+00,1.000000,211.000000
25%,2018-05-15 00:00:00,1.000000,1.710000e+02,24826.000000,233136.750000
50%,2018-12-19 00:00:00,1.000000,5.090000e+02,49951.000000,412597.500000
75%,2019-08-29 00:00:00,7.000000,3.000000e+03,75084.000000,502200.500000
max,2020-06-26 00:00:00,14049.000000,1.510944e+06,99999.000000,581031.000000
std,NaN,114.761496,2.991743e+04,28902.241989,167889.871825

In [28]:
users.describe()

             User_id            Age
count  100000.000000  100000.000000
mean    50000.500000      24.628580
std     28867.657797       2.971743
min         1.000000      18.000000
25%     25000.750000      23.000000
50%     50000.500000      24.000000
75%     75000.250000      26.000000
max    100000.000000      33.000000

In [29]:
restaurants.describe()

       Restaurant_id
count  148454.000000
mean   363505.455171
std    167881.655190
min       211.000000
25%    233516.500000
50%    412697.000000
75%    502245.500000
max    581031.000000

CHECKING RELATIONSHIPS

In [30]:
orders["User_id"].isin(users["User_id"]).value_counts()

User_id
True    150281
Name: count, dtype: int64

In [31]:
orders["Restaurant_id"].isin(
    restaurants["Restaurant_id"]
).value_counts()

Restaurant_id
True     148577
False      1704
Name: count, dtype: int64